
#config with properties
#with specific feign client name , default -> jplaceholder(name @FeignClient) :
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        #Interceptors
        requestInterceptors:
          com.example.kimhabspringopenfeign.config.CustomRequestInterceptor
        errorDecoder:
          com.example.kimhabspringopenfeign.customeError.CustomErrorDecoder
  # support Hystrix (fallback call)
  hystrix:
    enabled: true
  # circuitbreaker as call fallback class
  circuitbreaker:
    enabled: true

logging:
  level:
    com.example.kimhabspringopenfeign.feign_interface: DEBUG

#data

my-app:
  user: kimhab
  pass: 123